<?xml version="1.0" encoding="utf-8"?><Database Name="QLBenhNhan" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MOTHER-FUCKER;Initial Catalog=QLBenhNhan;Integrated Security=True" SettingsObjectName="GUI.Properties.Settings" SettingsPropertyName="QLBenhNhanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BenhNhan" Member="BenhNhans">
    <Type Name="BenhNhan">
      <Column Name="maBN" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngayNV" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="maKhoa" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhoaKham" Member="KhoaKhams">
    <Type Name="KhoaKham">
      <Column Name="maKhoa" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenKhoa" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>