<?xml version="1.0" encoding="utf-8"?><Database Name="QLLuong" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MOTHER-FUCKER;Initial Catalog=QLLuong;Integrated Security=True" SettingsObjectName="April13rd.Properties.Settings" SettingsPropertyName="QLLuongConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaVC" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhuCap" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonVi" Member="DonVis">
    <Type Name="DonVi">
      <Column Name="MaDV" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TenDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HSLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrinhDo" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaDV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>